# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calcli < Formula
  desc ""
  homepage "https://github.com/n0rdy/calcli"
  version "0.0.5"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.5/calcli_Darwin_x86_64.tar.gz"
      sha256 "aa173482ba242f86da1e4530dd488d6e2186626d662eef9826166845dee4cca0"

      def install
        bin.install "calcli"
      end
    end
    on_arm do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.5/calcli_Darwin_arm64.tar.gz"
      sha256 "179f465e51b69d6ae8476390214793d1333a687ef3ae598fae5e76ed38af5c76"

      def install
        bin.install "calcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.5/calcli_Linux_x86_64.tar.gz"
        sha256 "53e3f9c080e128e0a3408e7559f6548413327639d2825a95efc6975d229b10b7"

        def install
          bin.install "calcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.5/calcli_Linux_arm64.tar.gz"
        sha256 "96188fcc4cd42586397c5424b51cdc14b73ce78e9b21bed11d3d65b71759acf7"

        def install
          bin.install "calcli"
        end
      end
    end
  end
end
