# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calcli < Formula
  desc ""
  homepage "https://github.com/n0rdy/calcli"
  version "0.0.3"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.3/calcli_Darwin_x86_64.tar.gz"
      sha256 "227d0708c2fe369e24d1f5459389e7311a7312420755bd09661d0a45affadac3"

      def install
        bin.install "calcli"
      end
    end
    on_arm do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.3/calcli_Darwin_arm64.tar.gz"
      sha256 "5f0db43439b78b45323aeae22a485701b0546311893c5df7fba8d475b4bbab71"

      def install
        bin.install "calcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.3/calcli_Linux_x86_64.tar.gz"
        sha256 "37f416771e523e72b014c92ffe97364a75e17641f74529529fe74edf374f3b32"

        def install
          bin.install "calcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.3/calcli_Linux_arm64.tar.gz"
        sha256 "aa5dca7913b2e5393522a79fce5ddc6eb8a67e301c4cbcb07d64b2fe5ec81123"

        def install
          bin.install "calcli"
        end
      end
    end
  end
end
