# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calcli < Formula
  desc ""
  homepage "https://github.com/n0rdy/calcli"
  version "0.0.6"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.6/calcli_Darwin_x86_64.tar.gz"
      sha256 "a909466679d563260914d8fc170afbc9fb4af29c512164d49cca871281d0a6cf"

      def install
        bin.install "calcli"
      end
    end
    on_arm do
      url "https://github.com/n0rdy/calcli/releases/download/v0.0.6/calcli_Darwin_arm64.tar.gz"
      sha256 "9b9bad405a56ba1bda4890c5e5bfb6ec2a0888e03ec17787079707d003c9083d"

      def install
        bin.install "calcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.6/calcli_Linux_x86_64.tar.gz"
        sha256 "4dba586eb4d063f138b0b5e05a5ba61f613e96f5b7eb97882ce89d5b5d4163d1"

        def install
          bin.install "calcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/n0rdy/calcli/releases/download/v0.0.6/calcli_Linux_arm64.tar.gz"
        sha256 "a939f474dcdc1e09c598a2e16e5e12a099e89ebf76cc70a5115332e103fabc50"

        def install
          bin.install "calcli"
        end
      end
    end
  end
end
