# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remindme < Formula
  desc ""
  homepage "https://github.com/n0rdy/remindme"
  version "1.1.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/n0rdy/remindme/releases/download/v1.1.0/remindme_Darwin_arm64.tar.gz"
      sha256 "a4a9f1976dfd53b8dcd7e005f5bae34810009cb4be51dfbac0cdde8fd299b445"

      def install
        bin.install "remindme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/n0rdy/remindme/releases/download/v1.1.0/remindme_Darwin_x86_64.tar.gz"
      sha256 "aaebb9e690361c122d9a68198bed3619810680204d924a70a4a07851e251c897"

      def install
        bin.install "remindme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/n0rdy/remindme/releases/download/v1.1.0/remindme_Linux_x86_64.tar.gz"
      sha256 "ad643adfcbb1e19727c05dbd1cdac4b17eb002d7a5b77ee436656f0421161a6f"

      def install
        bin.install "remindme"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n0rdy/remindme/releases/download/v1.1.0/remindme_Linux_arm64.tar.gz"
      sha256 "b6574c85914236a91185738e35a1eefd6e4cf3f3ab6c6fbac5684f15a2b50d36"

      def install
        bin.install "remindme"
      end
    end
  end
end
