# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remindme < Formula
  desc ""
  homepage "https://github.com/n0rdy/remindme"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/n0rdy/remindme/releases/download/v1.0.0/remindme_Darwin_x86_64.tar.gz"
      sha256 "2b387a435ecfe11e4b6b6886539a2bd5ec6243141e954ca04e20e2871d897ca7"

      def install
        bin.install "remindme"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/n0rdy/remindme/releases/download/v1.0.0/remindme_Darwin_arm64.tar.gz"
      sha256 "b3e1fca3f5223a6933979755b7f84831e0842137d1377c5f8d918bbcd2d4d484"

      def install
        bin.install "remindme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/n0rdy/remindme/releases/download/v1.0.0/remindme_Linux_arm64.tar.gz"
      sha256 "771fad91678ab08b645205d84acefa75a3ebf014863e4de04760ca6ab5d64ce8"

      def install
        bin.install "remindme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/n0rdy/remindme/releases/download/v1.0.0/remindme_Linux_x86_64.tar.gz"
      sha256 "bd0d4116d48ac091fd07bed1de3df97a4f858c1c49d5a7fe69e0d0e078ca5429"

      def install
        bin.install "remindme"
      end
    end
  end
end
